# Configuración de la Base de Datos para el programa
db.url=jdbc:postgresql://localhost:5432/attizos_db
db.user=postgres
db.password=Abril2026Temporal

CLOUDINARY_CLOUD_NAME=dqbfhquvd
CLOUDINARY_API_KEY=139819442542135
CLOUDINARY_API_SECRET=x2iIGNYXWFHvtZtauuC_FTyZSPM